name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# TODO: add jobs that test on different hot platforms (windows, aarch64, etc)
# TODO: build examples on CI

jobs:
  btest:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          apt-get update
          apt-get install -qq -y rustup
          rustup toolchain install stable --no-self-update --profile minimal
      - name: Setup X Virtual Framebuffer for Wine
        run: |
          apt-get update
          apt-get install -qq -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Setup Wine
        runs: |
          dpkg --add-architecture i386
          apt-get update
          apt-get wine64 wine32:i386
          wineserver -k
          rm -rf ~/.wine
          winecfg
      - name: Correct image difference
        run: |
          apt-get update
          apt-get install -qq -y git xxd
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -qq -y clang make fasm mingw-w64 gcc-aarch64-linux-gnu qemu-user
          git clone https://git.sr.ht/~rabbits/uxn11
          cd uxn11
          make cli
      - name: Run Tests
        run: PATH=$(realpath uxn11/bin):$PATH make btest
